# Generated by Django 4.2.7 on 2023-11-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Authors_app', '0003_alter_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
