# Generated by Django 4.2.7 on 2023-11-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Authors_app', '0004_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='befor adding notes'),
            preserve_default=False,
        ),
    ]
