# Generated by Django 4.2.7 on 2023-12-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Authors_app', '0006_alter_author_notes_alter_book_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='Books_Authors_app.book'),
        ),
    ]
