# Generated by Django 4.2.7 on 2023-11-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0007_remove_ninjas_dojo_ninjas_dojos_alter_dojo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
